class VariablesMongoDb:
    name = 'name'
    is_consumer = 'is_consumer'
    create_date = 'create_date'
    category_id = 'category_id'
    response_id = 'response_id'
    active = 'active'
    repair_history = 'repair_history'
    position_id = 'position_id'
    has_response = 'has_response'
    stock_number = 'stock_number'
    update_history='update_history'
